<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateRedirectsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('redirects', function (Blueprint $table) {
            $table->increments('id');
            $table->boolean('active')->default(false);
            $table->enum('type', ['permanent', 'temporary']);
            $table->text('origin_url');
            $table->unsignedInteger('page_id')->nullable();
            $table->unsignedInteger('blog_post_id')->nullable();
            $table->text('link')->nullable();
            $table->string('target', 10)->nullable();
            $table->nullableTimestamps();

            $table->index('page_id', 'page_id');
            $table->index('blog_post_id', 'blog_post_id');

            $table->foreign('page_id', 'redirects_ibfk_1')->references('id')->on('pages')->onDelete('CASCADE')->onUpdate('CASCADE');
            $table->foreign('blog_post_id', 'redirects_ibfk_2')->references('id')->on('blog_posts')->onDelete('CASCADE')->onUpdate('CASCADE');
        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('redirects');
    }
}
